### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by dantrevino** [creationix/wheat#1]
dan@entropy:~$ wheat projects/howtonode.org/
    Starting wheat server using git repo at projects/howtonode.org/
    node-router server instance at http://127.0.0.1:8080/
    127.0.0.1 - - [Fri, 16 Apr 2010 01:48:10 GMT] "GET / HTTP/1.1" 200 - "" "Mozilla/5.0"
    TypeError: Cannot read property 'apply' of undefined
    at ServerResponse.end (/home/dan/.node_libraries/wheat/node-router.js:54:5)
    at Function.responder (/home/dan/.node_libraries/wheat.js:668:18)
    at Function.<anonymous> (/home/dan/.node_libraries/wheat/git.js:91:23)
    at next (/home/dan/.node_libraries/wheat/step.js:49:23)
    at Function.buildHeaders (/home/dan/.node_libraries/wheat.js:475:11)
    at next (/home/dan/.node_libraries/wheat/step.js:49:23)
    at Step (/home/dan/.node_libraries/wheat/step.js:90:3)
    at postProcess (/home/dan/.node_libraries/wheat.js:446:5)
    at Function.callPostProcess (/home/dan/.node_libraries/wheat.js:513:11)
    at Function.next (/home/dan/.node_libraries/wheat/step.js:49:23)
dan@entropy:~$

**Comment by creationix** [comment]
Not sure what to say, are you on node v0.1.90 or newer?  Have you modified the code in wheat in any way?

**Comment by dantrevino** [comment]
I thought i was running 1.9... apparently i was running 1.3xx ... upgrading fixed the issue ... once again... thanks!

**Comment by creationix** [comment]
http://github.com/creationix/nvm :)
