### ISSUE TITLE
Problem with Node 0.6?

### ISSUE THREAD

**Issue by sanbor** [creationix/wheat#36]
I did npm install wheat, then I also installed the packages stack and creationix. When I run node server/server.js I got this

sanbor@sanbor:~/Projects/Playground/howtonode.org$ node server/server.js 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:376:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/wheat/lib/wheat.js:23:8)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/home/sanbor/Projects/Playground/howtonode.org/server/server.js:8:3)
    at Module._compile (module.js:432:26)

**Comment by cronopio** [comment]
yes, [here](https://github.com/creationix/wheat/blob/master/lib/wheat.js#L23) the `unshift()` method deprecated on 0.6

**Comment by TooTallNate** [comment]
I've added a pull request fixing wheat for node v0.6.0 in #38.

**Comment by ghost** [comment]
I am having this issue too

**Comment by cronopio** [comment]
Check you have "version": "0.2.4"

https://github.com/creationix/wheat/compare/03571...v0.2.4
