### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by garryyao** [creationix/wheat#5]
Got a Connect server validation error when starting wheat:

```
Error: Each layer must have a route and a handle function
    at Server.use (/home/garry/.node_libraries/wheat/connect/index.js:146:15)
    at Server.<anonymous> (/home/garry/.node_libraries/wheat/connect/index.js:102:14)
    at Array.forEach (native)
    at new Server (/home/garry/.node_libraries/wheat/connect/index.js:101:12)
    at Object.createServer (/home/garry/.node_libraries/wheat/connect/index.js:270:12)
    at Object.<anonymous> (/home/garry/bin/wheat:21:9)
    at Module._compile (module:384:23)
    at Module._loadScriptSync (module:393:8)
    at Module.loadSync (module:296:10)
    at Object.runMain (module:447:22)
```

**Comment by TooTallNate** [comment]
I assume you updated the `connectpkg` submodule to the newest commit? I forked and addressed this issue. What what required was retrofitting the `bin/wheat` executable to use the current Connect API.

http://github.com/TooTallNate/wheat/commit/cfb9f546fe26a4092f1e023627aabed01af5d72a

**Comment by garryyao** [comment]
Works well, thanks.
http://github.com/TooTallNate/wheat/commit/cfb9f546fe26a4092f1e023627aabed01af5d72a#commitcomment-100779

**Comment by creationix** [comment]
Ok, I pulled the changes in, my version should work now too.

**Comment by creationix** [comment]
Now the npm dependency chain pulls a new enough version of connect.  This should work out of the box.
